version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - database
  database:
    image: postgres:15
    container_name: tenant_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tenant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data